define

tag sub entity
    has name
    plays describes
    plays in_tag_cluster;

tag_cluster sub entity
    has name
    plays parent_tag
    plays specifies
    plays sub_specifies
    plays in_tag_cluster; 

packing_type sub entity
    plays pack_with
    has cost;

category sub entity
    has name
    plays parent_category;

item sub entity
    has name
    plays specified
    plays sub_specificied
    plays in_category;

inventory sub entity
    has uid
    has cft
    plays packed
    plays described;

name sub attribute datatype string;
uid sub attribute datatype string;
cft sub attribute datatype long;
cost sub attribute datatype double;

described sub role;
describes sub role;
packed sub role;
pack_with sub role;
parent_tag sub role;
in_tag_cluster sub role;
parent_category sub role;
in_category sub role;

description sub relationship
    relates described
    relates describes;

packs sub relationship
    relates packed
    relates pack_with;

tag_group sub relationship
    relates parent_tag
    relates in_tag_cluster;

category_group sub relationship
    relates parent_category
    relates in_category;

specification sub relationship
    relates specifies
    relates specified;

sub_specification sub relationship
    relates sub_specifies
    relates sub_specificied;


specificationOfSubTags1 sub rule 
when {
        (parent_tag:$p, in_tag_cluster: $c) isa tag_group; 
        (specified: $item, $p) isa specification;
        $c isa tag_cluster;
    } then{
        (sub_specifies: $c, sub_specificied: $item) isa sub_specification;
    };

specificationOfSubTags2 sub rule 
when {
        (parent_tag:$p, in_tag_cluster: $c) isa tag_group; 
        (sub_specificied: $item, $p) isa sub_specification;
        $c isa tag_cluster;
    } then{
        (sub_specifies: $c, sub_specificied: $item) isa sub_specification;
    };